/** Draft PR title and body (§8 step 8). A template over run data, no agent involved. */
import type { GateResult } from '../gates';
import { clipMiddle, clipTail, demoteHeadings, join } from './format';
import type { PrBodyInput, VerifyResultInput } from './types';

/** GitHub rejects bodies longer than this. */
export const PR_BODY_MAX_CHARS = 65_536;
export const PR_TITLE_MAX_CHARS = 70;

export interface PrText {
  readonly title: string;
  readonly body: string;
  /** Something had to be shortened to fit GitHub's limit. */
  readonly truncated: boolean;
}

function cell(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim() || ' ';
}

export function buildPrTitle(title: string, prefix?: string | null): string {
  const clean = title.replace(/\s+/g, ' ').trim() || 'Legion run';
  const full = prefix?.trim() ? `${prefix.trim()}: ${clean}` : clean;
  return full.length <= PR_TITLE_MAX_CHARS ? full : `${full.slice(0, PR_TITLE_MAX_CHARS - 1).trimEnd()}…`;
}

function isGateResult(r: VerifyResultInput | GateResult): r is GateResult {
  return 'name' in r && 'status' in r && typeof r.name === 'string' && typeof r.status === 'string';
}

function verifyOutcome(r: VerifyResultInput | GateResult): string {
  if (isGateResult(r)) {
    if (r.status === 'pass') return '✅ passed';
    if (r.status === 'skipped') return '⏭️ skipped';
    const why = r.kind !== 'command' ? r.summary : r.exitCode === null ? 'killed / timed out' : `exit ${r.exitCode}`;
    return r.blocking ? `❌ ${why}` : `⚠️ warning: ${why}`;
  }
  if (r.exitCode === null) return '⚠️ killed / timed out';
  return r.exitCode === 0 ? '✅ passed' : `❌ exit ${r.exitCode}`;
}

function failed(r: VerifyResultInput | GateResult): boolean {
  return isGateResult(r) ? r.status === 'fail' : r.exitCode !== 0;
}

function duration(r: VerifyResultInput): string {
  return r.durationMs != null ? `${(r.durationMs / 1000).toFixed(1)}s` : '-';
}

function code(text: string): string {
  return `\`${cell(text).replace(/`/g, "'")}\``;
}

/** Minor findings: full bodies, titles only, or a count. */
type MinorMode = 'full' | 'titles' | 'count';

export function buildPrBody(input: PrBodyInput): PrText {
  const render = (summaryMax: number, minor: MinorMode, tailMax: number): string => {
    const header = join(
      input.closes ? `Closes ${input.closes}` : null,
      `## Summary\n\n${demoteHeadings(clipMiddle(input.summary.trim() || '(no summary)', summaryMax), 1)}`,
      input.issueUrl ? `Issue: ${input.issueUrl}` : null,
    );
    const tasks =
      input.tasks.length === 0
        ? null
        : [
            '## Tasks',
            '',
            '| Task | Title | Status | Coder | Reviewer | Verdict | Fix rounds |',
            '|---|---|---|---|---|---|---|',
            ...input.tasks.map(
              (t) =>
                `| ${cell(t.nodeId)} | ${cell(t.title)} | ${cell(t.status)} | ${cell(t.coderEngine)} | ${cell(t.reviewerEngine ?? '-')} | ${cell(t.verdict ?? '-')} | ${t.fixRounds} |`,
            ),
          ].join('\n');
    // Gate results get a Gate column; legacy rows (no gate name) keep the command-only table.
    const gated = input.verification.some(isGateResult);
    const verification =
      input.verification.length === 0
        ? '## Verification\n\nNo verification commands were run.'
        : [
            '## Verification',
            '',
            gated ? '| Gate | Command | Result | Duration |' : '| Command | Result | Duration |',
            gated ? '|---|---|---|---|' : '|---|---|---|',
            ...input.verification.map((r) =>
              gated
                ? `| ${isGateResult(r) ? cell(r.name) : '-'} | ${code(r.command)} | ${cell(verifyOutcome(r))} | ${duration(r)} |`
                : `| ${code(r.command)} | ${verifyOutcome(r)} | ${duration(r)} |`,
            ),
            ...input.verification
              .filter((r) => failed(r) && r.outputTail.trim() && tailMax > 0)
              .map(
                (r) =>
                  `\n<details><summary>Output of <code>${escapeHtml(isGateResult(r) ? r.name : r.command)}</code></summary>\n\n\`\`\`\`text\n${clipTail(r.outputTail.trim(), tailMax).replace(/````/g, "'''")}\n\`\`\`\`\n\n</details>`,
              ),
          ].join('\n');
    const minorFindings = renderMinor(input, minor);
    const attachments = input.attachments?.length
      ? `Attachments: ${input.attachments.map((name) => `\`${name.replace(/`/g, "'")}\``).join(', ')}`
      : null;
    const noteLines = [...(input.notes ?? []), ...(attachments ? [attachments] : [])];
    const notes = noteLines.length > 0 ? `## Notes\n\n${noteLines.map((n) => `- ${n}`).join('\n')}` : null;
    const footer = `---\n<sub>Generated by Legion · run \`${input.runId}\` · \`${input.integrationBranch}\` → \`${input.baseRef}\`</sub>`;
    return join(header, tasks, verification, minorFindings, notes, footer);
  };

  const attempts: [number, MinorMode, number][] = [
    [20_000, 'full', 3_000],
    [20_000, 'titles', 1_500],
    [8_000, 'titles', 500],
    [8_000, 'count', 0],
    [2_000, 'count', 0],
  ];
  for (const [i, [summaryMax, minor, tailMax]] of attempts.entries()) {
    const body = render(summaryMax, minor, tailMax);
    if (body.length <= PR_BODY_MAX_CHARS) {
      const truncated = i > 0 || input.summary.trim().length > summaryMax;
      return { title: buildPrTitle(input.title, input.titlePrefix), body, truncated };
    }
  }
  const last = render(2_000, 'count', 0);
  const marker = '\n\n[… truncated to fit GitHub’s 65,536 character limit …]';
  return {
    title: buildPrTitle(input.title, input.titlePrefix),
    body: `${last.slice(0, PR_BODY_MAX_CHARS - marker.length)}${marker}`,
    truncated: true,
  };
}

function renderMinor(input: PrBodyInput, mode: MinorMode): string | null {
  const findings = input.minorFindings;
  if (findings.length === 0) return null;
  const heading = `## Minor review findings\n\nNon-blocking findings from the reviewers (${findings.length}), not addressed in this PR.`;
  if (mode === 'count') return `${heading} See run \`${input.runId}\` in Legion for details.`;
  const items = findings.map(({ nodeId, finding: f }) => {
    const where = f.file ? ` (\`${f.file}${f.line != null ? `:${f.line}` : ''}\`)` : '';
    const head = `- **${nodeId ?? 'final'}** [${f.severity}] ${f.title.replace(/\s+/g, ' ').trim()}${where}`;
    if (mode === 'titles') return head;
    const body = clipMiddle(f.body.trim(), 1_000).replace(/\n/g, '\n  ');
    const fix = f.suggestedFix?.trim()
      ? `\n  Suggested fix: ${clipMiddle(f.suggestedFix.trim(), 500).replace(/\n/g, '\n  ')}`
      : '';
    return `${head}\n  ${body}${fix}`;
  });
  return `${heading}\n\n<details><summary>Show findings</summary>\n\n${items.join('\n')}\n\n</details>`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
