/** Scope check (§8 Verify): actual changed files vs the node's declared `touches`. */
import type { TaskNode } from '@shared/domain';
import { globMatchesPath, normalizeGlob } from './glob';

export interface ScopeReport {
  /** Changed files covered by a create/modify touch. */
  readonly inScope: readonly string[];
  /** Changed files not covered by any write touch (includes `readOnly`). */
  readonly outOfScope: readonly string[];
  /** Out-of-scope files the node declared as `read` only. */
  readonly readOnly: readonly string[];
  /** Write touches no changed file matched (often fine: "may touch"). */
  readonly unusedTouches: readonly string[];
  readonly ok: boolean;
}

/**
 * Classify changed paths (repo-relative, e.g. from `git diff --name-only startSha..HEAD`; for renames pass
 * both paths). `alwaysAllowed` globs never count as out of scope (e.g. a lockfile regenerated by the install
 * command).
 */
export function checkScope(
  node: Pick<TaskNode, 'touches'>,
  changedPaths: readonly string[],
  alwaysAllowed: readonly string[] = [],
): ScopeReport {
  const writes = node.touches.filter((t) => t.mode !== 'read').map((t) => normalizeGlob(t.glob));
  const reads = node.touches.filter((t) => t.mode === 'read').map((t) => normalizeGlob(t.glob));
  const inScope: string[] = [];
  const outOfScope: string[] = [];
  const readOnly: string[] = [];
  const used = new Set<string>();
  for (const path of [...new Set(changedPaths.map(normalizeGlob))].sort()) {
    const matched = writes.filter((g) => globMatchesPath(g, path));
    for (const g of matched) used.add(g);
    if (matched.length > 0 || alwaysAllowed.some((g) => globMatchesPath(g, path))) {
      inScope.push(path);
      continue;
    }
    outOfScope.push(path);
    if (reads.some((g) => globMatchesPath(g, path))) readOnly.push(path);
  }
  const unusedTouches = [...new Set(writes)].filter((g) => !used.has(g));
  return { inScope, outOfScope, readOnly, unusedTouches, ok: outOfScope.length === 0 };
}
