/** Scope check (§8 Verify): actual changed files vs the node's declared `touches`. */
import type { GateScopeMode, TaskNode } from '@shared/domain';
import type { GateResult } from './gates';
import { globMatchesPath, normalizeGlob } from './glob';

export interface ScopeReport {
  /** Changed files covered by a create/modify touch. */
  readonly inScope: readonly string[];
  /** Changed files not covered by any write touch (includes `readOnly`). */
  readonly outOfScope: readonly string[];
  /** Out-of-scope files the node declared as `read` only. */
  readonly readOnly: readonly string[];
  /** Write touches no changed file matched (often fine: "may touch"). */
  readonly unusedTouches: readonly string[];
  readonly ok: boolean;
}

/**
 * Classify changed paths (repo-relative, e.g. from `git diff --name-only startSha..HEAD`; for renames pass
 * both paths). `alwaysAllowed` globs never count as out of scope (e.g. a lockfile regenerated by the install
 * command).
 */
export function checkScope(
  node: Pick<TaskNode, 'touches'>,
  changedPaths: readonly string[],
  alwaysAllowed: readonly string[] = [],
): ScopeReport {
  const writes = node.touches.filter((t) => t.mode !== 'read').map((t) => normalizeGlob(t.glob));
  const reads = node.touches.filter((t) => t.mode === 'read').map((t) => normalizeGlob(t.glob));
  const inScope: string[] = [];
  const outOfScope: string[] = [];
  const readOnly: string[] = [];
  const used = new Set<string>();
  for (const path of [...new Set(changedPaths.map(normalizeGlob))].sort()) {
    const matched = writes.filter((g) => globMatchesPath(g, path));
    for (const g of matched) used.add(g);
    if (matched.length > 0 || alwaysAllowed.some((g) => globMatchesPath(g, path))) {
      inScope.push(path);
      continue;
    }
    outOfScope.push(path);
    if (reads.some((g) => globMatchesPath(g, path))) readOnly.push(path);
  }
  const unusedTouches = [...new Set(writes)].filter((g) => !used.has(g));
  return { inScope, outOfScope, readOnly, unusedTouches, ok: outOfScope.length === 0 };
}

/** Out-of-scope files the summary names before `+N more`. */
const SUMMARY_FILES = 3;

/**
 * The built-in `scope` gate: pass when every changed file is covered by a write touch (or `alwaysAllowed`),
 * else fail, blocking only in `block` mode.
 */
export function scopeGateResult(report: ScopeReport, mode: GateScopeMode): GateResult {
  const outside = report.outOfScope;
  const passed = outside.length === 0;
  const total = report.inScope.length + outside.length;
  const named = outside.slice(0, SUMMARY_FILES).join(', ');
  const more = outside.length > SUMMARY_FILES ? ` +${outside.length - SUMMARY_FILES} more` : '';
  const readOnly = new Set(report.readOnly);
  return {
    name: 'scope',
    kind: 'scope',
    command: 'legion:scope',
    source: 'builtin',
    status: passed ? 'pass' : 'fail',
    blocking: mode === 'block',
    exitCode: passed ? 0 : 1,
    durationMs: null,
    summary: passed ? `${total}/${total} files declared` : `${outside.length} outside: ${named}${more}`,
    outputTail: passed
      ? ''
      : [
          `Changed files outside the task's declared touches (${outside.length}):`,
          ...outside.map((p) => `- ${p}${readOnly.has(p) ? ' (declared read-only)' : ''}`),
          '',
          'Revert these changes, or keep each one minimal and justify it in your summary.',
        ].join('\n'),
  };
}
